#!/usr/bin/env bash
# Generates .env.simulith.local for Cypress E2E against local Simulith.
# Requires: Simulith up, AWS profile simulith, Cognito SSM params from infra apply.
set -eu

export MSYS2_ARG_CONV_EXCL="${MSYS2_ARG_CONV_EXCL:-*}"

FRONTEND_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SERVERLESS_ROOT="${SERVERLESS_ROOT:-$(cd "$FRONTEND_ROOT/../loyalty-program-serverless" 2>/dev/null && pwd || true)}"

if [[ -n "$SERVERLESS_ROOT" && -f "$SERVERLESS_ROOT/scripts/simulith-env.sh" ]]; then
  # shellcheck source=/dev/null
  source "$SERVERLESS_ROOT/scripts/simulith-env.sh"
fi

ENDPOINT="${ENDPOINT:-${SIMULITH_ENDPOINT:-http://127.0.0.1.sslip.io:4567}}"
SIMULITH_HOST_PORT="${SIMULITH_HOST_PORT:-4567}"
REGION="${AWS_DEFAULT_REGION:-us-east-1}"

if [[ -z "${AWS_PROFILE:-}" ]]; then
  export AWS_PROFILE=simulith
fi
if [[ -n "$SERVERLESS_ROOT" && -f "$SERVERLESS_ROOT/.aws/config" ]]; then
  export AWS_CONFIG_FILE="${AWS_CONFIG_FILE:-$SERVERLESS_ROOT/.aws/config}"
  export AWS_SHARED_CREDENTIALS_FILE="${AWS_SHARED_CREDENTIALS_FILE:-$SERVERLESS_ROOT/.aws/credentials}"
fi
export AWS_SDK_LOAD_CONFIG=1

AWS_OPTS=(--region "$REGION" --endpoint-url "$ENDPOINT")

echo "=== Prepare Simulith E2E env ==="
echo "  Endpoint: $ENDPOINT"

HEALTH="$(curl -sf "$ENDPOINT/health" 2>/dev/null || true)"
if [[ -z "$HEALTH" ]]; then
  echo "ERROR: Simulith health check failed at $ENDPOINT/health"
  echo "  Start: cd loyalty-program-serverless && ./scripts/simulith-start.sh"
  exit 1
fi
echo "  Health:   $HEALTH"

POOL_ID="${VITE_COGNITO_USER_POOL_ID:-$(aws "${AWS_OPTS[@]}" ssm get-parameter \
  --name /LOYALEASY/DEV/COGNITO_USER_POOL_ID --query Parameter.Value --output text 2>/dev/null || true)}"
CLIENT_ID="${VITE_COGNITO_CLIENT_ID:-$(aws "${AWS_OPTS[@]}" ssm get-parameter \
  --name /LOYALEASY/DEV/COGNITO_CLIENT_ID --query Parameter.Value --output text 2>/dev/null || true)}"

ENV_FILE="$FRONTEND_ROOT/.env.simulith.local"

if [[ -z "$POOL_ID" || -z "$CLIENT_ID" || "$POOL_ID" == "None" || "$CLIENT_ID" == "None" ]]; then
  if [[ -f "$ENV_FILE" ]] && grep -q 'VITE_COGNITO_USER_POOL_ID=us-east-1_' "$ENV_FILE" 2>/dev/null; then
    echo "  SSM:      skipped (using existing $ENV_FILE)"
    echo "  Tip: run deploy-frontend-simulith.sh once to refresh Cognito IDs"
    exit 0
  fi
  echo "ERROR: Could not read Cognito IDs from SSM."
  echo "  Fix: apply cognito/ infra, or copy env.simulith.example → .env.simulith.local with real IDs"
  echo "  Or: npm run deploy:simulith (generates .env.simulith.local)"
  exit 1
fi

APP_ORIGIN="${APP_ORIGIN:-http://dev.loyaleasy.com:${SIMULITH_HOST_PORT}}"

cat > "$ENV_FILE" <<EOF
# Generated by prepare-simulith-e2e-env.sh — do not commit
VITE_API_BASE_AUTH=$APP_ORIGIN
VITE_API_BASE_APP=$APP_ORIGIN
VITE_PROGRAM_ID=PCM
VITE_COGNITO_USER_POOL_ID=$POOL_ID
VITE_COGNITO_CLIENT_ID=$CLIENT_ID
VITE_COGNITO_REGION=$REGION
VITE_COGNITO_ENDPOINT=$APP_ORIGIN
EOF

echo "  Wrote:    $ENV_FILE"
echo "  Cognito:  pool=$POOL_ID client=${CLIENT_ID:0:8}..."
echo ""
echo "Hosts (required for Cognito): 127.0.0.1 dev.loyaleasy.com"
echo "Cypress baseUrl: http://dev.loyaleasy.com:51730"
